// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxRO4_2k9fCLzcoYukUImFiwgGou8dqp0',
    appId: '1:896846452358:web:321bb8b751fef3dd856307',
    messagingSenderId: '896846452358',
    projectId: 'stp-flutter-7cc1b',
    authDomain: 'stp-flutter-7cc1b.firebaseapp.com',
    storageBucket: 'stp-flutter-7cc1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB-6QZB1ckCE1E5llpZVF8saidKxGQhVU',
    appId: '1:896846452358:android:613b61ad3dca2551856307',
    messagingSenderId: '896846452358',
    projectId: 'stp-flutter-7cc1b',
    storageBucket: 'stp-flutter-7cc1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoOnJ6c6-WaQjIF7pRw0B9AFJmGDnsgcA',
    appId: '1:896846452358:ios:c4d9e5c690f751b1856307',
    messagingSenderId: '896846452358',
    projectId: 'stp-flutter-7cc1b',
    storageBucket: 'stp-flutter-7cc1b.appspot.com',
    iosBundleId: 'ru.vsu.stp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoOnJ6c6-WaQjIF7pRw0B9AFJmGDnsgcA',
    appId: '1:896846452358:ios:f2ac72a77a7f2ea2856307',
    messagingSenderId: '896846452358',
    projectId: 'stp-flutter-7cc1b',
    storageBucket: 'stp-flutter-7cc1b.appspot.com',
    iosBundleId: 'ru.vsu.stp.RunnerTests',
  );
}
